compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

packageExtensions:
  # ESLint plugins need to forward typescript to @typescript-eslint/utils
  '@tanstack/eslint-plugin-query@*':
    peerDependencies:
      typescript: '*'
  eslint-plugin-jest@*:
    peerDependencies:
      typescript: '*'
  eslint-plugin-testing-library@*:
    peerDependencies:
      typescript: '*'
  # @commitlint needs to forward these to cosmiconfig-typescript-loader
  '@commitlint/cli@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '*'
      typescript: '*'
  # electron-builder-squirrel-windows is optional (Windows only)
  app-builder-lib@*:
    peerDependenciesMeta:
      electron-builder-squirrel-windows:
        optional: true

enableHardenedMode: false

enableScripts: false

nodeLinker: node-modules

plugins:
  - checksum: f850d56621bac3235ad891222942ac396f122ac3308e8e9e36bce43e1bcb8697cad4c81529fc55b164fc0f5e45aa8dc1585fa90bd1e0fa9d6a05f3a85e080ebb
    path: .yarn/plugins/@yarnpkg/plugin-licenses.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-licenses/v0.13.0/bundles/@yarnpkg/plugin-licenses.js'
  - checksum: 006d0325e832b7267fa88084a62d319de313ca2541dca62f8fea3125f095a4cc1b8791897f1d803d38179a972aa2152533d11525e463fb8073ca358ee8601f44
    path: .yarn/plugins/@yarnpkg/plugin-spdx.cjs
    spec: 'https://raw.githubusercontent.com/spdx/yarn-plugin-spdx/main/bundles/@yarnpkg/plugin-spdx.js'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
