version = 1

[[annotations]]
path = "*.md"
precedence = "override"
SPDX-FileCopyrightText = "Meta Platforms, Inc. and its affiliates\nTNG Technology Consulting GmbH <https://www.tngtech.com>"
SPDX-License-Identifier = "CC0-1.0"
