// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
// SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
//
// SPDX-License-Identifier: Apache-2.0
export const text = {
  attributionColumn: {
    packageSubPanel: {
      confidence: 'Confidence',
      copyToClipboard: 'Copy to clipboard',
      noLinkToOpen: 'No link to open. Please enter a URL.',
      openLinkInBrowser: 'Open repository URL in browser',
      packageName: 'Package Name',
      packageNamespace: 'Package Namespace',
      packageType: 'Package Type',
      packageVersion: 'Package Version',
      pasteFromClipboard: 'Paste from clipboard',
      purl: 'PURL',
      repositoryUrl: 'Repository URL',
    },
    commonEcosystems: 'Common Ecosystems',
    commonLicenses: 'Common Licenses',
    copyToClipboardSuccess: 'Copied to clipboard',
    description: 'Description',
    enrichFailure: 'No package found with these coordinates',
    enrichSuccess: 'Added information where possible',
    enrichNoop: 'No more information found',
    getUrlAndLegal: 'Get missing URL and legal information from the web',
    homepage: 'Homepage',
    invalidPurl: 'INVALID PURL',
    legalInformation: 'Legal Information',
    licenseName: 'License Name',
    licenseTextModified: '(License text modified)',
    attributions: 'Attributions',
    occurrence: 'occurrence',
    openSourceInsights: 'Open Source Insights',
    origin: 'Origin',
    originallyFrom: 'Originally from ',
    packageCoordinates: 'Package Coordinates',
    pasteFromClipboardFailed: 'Clipboard does not contain a valid PURL',
    pasteFromClipboardSuccess: 'Pasted from clipboard',
    source: 'Source',
    useAutocompleteSuggestion:
      'Adopt all coordinates and legal information from suggestion',
    link: 'Link',
    save: 'Save',
    confirm: 'Confirm',
    delete: 'Delete',
    revert: 'Revert',
    restore: 'Restore',
    unlink: 'Unlink',
    replace: 'Use as Replacement',
    compareToOriginal: 'Compare to original',
  },
  packageLists: {
    useAsAttribution: 'Use as attribution on selected resource',
    create: 'Create new attribution',
    attribution: 'attribution',
    attributionsPanelTitle: (numberTotal: number, numberOnResource: number) =>
      `Attributions (${new Intl.NumberFormat().format(numberTotal)} total, ${new Intl.NumberFormat().format(numberOnResource)} on resource)`,
    confirm: 'Confirm',
    delete: 'Delete',
    hideDeleted: 'Hide deleted',
    replace: 'Replace',
    cancelReplace: 'Cancel replace',
    restore: 'Restore',
    showDeleted: 'Show deleted',
    signal: 'signal',
    signalsPanelTitle: (numberTotal: number, numberOnResource: number) =>
      `Signals (${new Intl.NumberFormat().format(numberTotal)} total, ${new Intl.NumberFormat().format(numberOnResource)} on resource)`,
    unknownSource: 'Unknown Source',
    jumpNext: 'Jump to next section',
    jumpPrevious: 'Jump to previous section',
    jumpStart: 'Jump to section start',
    scrollToTop: 'Scroll to top',
    scrollToBottom: 'Scroll to bottom',
    searchAttributions: 'Search attributions',
    searchSignals: 'Search signals',
    selectReplacement: 'Please select an attribution or signal as replacement',
    selectLicense: 'Select a license',
    incompleteAttributions: 'This resource has incomplete attributions',
    clearFilters: 'Clear filters',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
  },
  buttons: {
    cancel: 'Cancel',
    close: 'Close',
    filter: 'Filter',
    ok: 'OK',
    search: 'Search',
    sort: 'Sort',
  },
  modifyWasPreferredPopup: {
    title: 'Modifying Previously Preferred Attribution',
    message:
      'You are about to modify an attribution that was preferred in the past. Are you sure you want to continue? The attribution will no longer be marked with a',
  },
  processPopup: {
    title: 'Processing…',
  },
  projectStatisticsPopup: {
    title: 'Project Statistics',
    toggleStartupCheckbox: 'Show project statistics on startup',
  },
  unsavedChangesPopup: {
    title: 'Unsaved Changes',
    message: 'You have unsaved changes. What would you like to do?',
    discard: 'Discard and Proceed',
  },
  resourceBrowser: {
    allResources: (numberOfResources: number) =>
      `All Resources (${new Intl.NumberFormat().format(numberOfResources)})`,
    linkedResources: (numberOfResources: number) =>
      `Linked Resources (${new Intl.NumberFormat().format(numberOfResources)})`,
    searchAllPlaceholder: 'Search all resources',
    searchLinkedPlaceholder: 'Search linked resources',
    hasHighlyCriticalSignals: 'Has highly critical signals',
    hasMediumCriticalSignals: 'Has medium critical signals',
    hasSignals: 'Has signals',
  },
  auditingOptions: {
    add: 'Add Auditing Option',
    confidence: 'Confidence',
    currentlyPreferred: 'Currently Preferred',
    excludedFromNotice: 'Excluded from Notice',
    followUp: 'Needs Follow-Up',
    modifiedPreferred: 'Modified Previously Preferred',
    needsReview: 'Needs Review by QA',
    preselected: 'Pre-selected',
    previouslyPreferred: 'Previously Preferred',
    highCriticality: 'High Criticality',
    mediumCriticality: 'Medium Criticality',
  },
  errors: {
    unknown: 'unknown',
  },
  updateAppPopup: {
    title: 'Check for Updates',
    loading: 'Loading…',
    noUpdateAvailable: 'You have the latest version of OpossumUI installed.',
    updateAvailable: 'There is a newer version of OpossumUI available:',
    fetchFailed: (message: string) =>
      `Failed to fetch latest release information: ${message}`,
  },
  replaceAttributionsPopup: {
    replace: 'Replace',
    removeAttributions: (attributions: string) =>
      `This action will remove the following ${attributions}:`,
    replacement: 'The replacement will be:',
    title: 'Replace Attributions',
  },
  saveAttributionsPopup: {
    titleSave: 'Save Attributions',
    titleConfirm: 'Confirm Attributions',
    updateAttributions: (attributions: string, resources: string) =>
      `This action will update the following ${attributions} on ${resources}:`,
    updateGlobally: 'Update on All',
    updateLocally: 'Update only on Selected',
    update: 'Update',
    resource: 'resource',
  },
  deleteAttributionsPopup: {
    title: 'Delete Attributions',
    deleteAttributions: (attributions: string, resources: string) =>
      `This action will permanently remove the following ${attributions} from ${resources}:`,
    deleteGlobally: 'Delete on All',
    deleteLocally: 'Delete only on Selected',
    delete: 'Delete',
    resource: 'resource',
  },
  filters: {
    firstParty: 'First Party',
    thirdParty: 'Third Party',
    excludedFromNotice: 'Excluded from Notice',
    incomplete: 'Incomplete',
    lowConfidence: 'Low Confidence',
    needsFollowUp: 'Needs Follow-Up',
    needsReview: 'Needs Review by QA',
    preSelected: 'Pre-selected',
    currentlyPreferred: 'Currently Preferred',
    previouslyPreferred: 'Previously Preferred',
  },
  sortings: {
    criticality: 'By Criticality',
    name: 'By Name',
    occurrence: 'By Occurrence',
  },
  resourceDetails: {
    searchTooltip: 'Search',
    sortTooltip: 'Sort',
  },
  relations: {
    children: 'On Children',
    outside: 'Outside of Resource',
    parents: 'On Parents',
    resource: 'On Resource',
  },
  reportView: {
    openInAuditView: 'Open in Audit View',
  },
  diffPopup: {
    title: 'Compare to Original Signal',
    applyChanges: 'Apply changes',
    revertAll: 'Revert all',
  },
} as const;
