@startmindmap
<style>
mindmapDiagram {
  node {
    BackgroundColor white
    ' Shadowing 0.0
    LineColor #a80036
  }
  arrow {
    ' LineStyle 4
    LineThickness 2
    LineColor #a80036
  }
  :depth(0) {
    FontSize 40
  }
  :depth(1) {
      BackGroundColor white
  }
  ' boxless {
  '   FontColor darkgreen
  ' }
  .todo {
    FontColor gray
  }
}
</style>
* <b>OpossumUI</b>
--_ Opossum File (.opossum)
--_ Opossum Legacy File (.json/.json.gz)
--- oss-review-toolkit/ort
----_ OSS Review Toolkit JSON / YAML
--_ ScanCode JSON
--_ OWASP Dependency check JSON
++_ SPDX-2.2 (Lite) JSON / YAML
++_ CSV attributions list
++_ CSV follow-up list
@endmindmap
