// SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
// SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
//
// SPDX-License-Identifier: Apache-2.0

export const menuItemIds = {
  about: 'about',
  aboutChromiumNotices: 'about-chromium-notices',
  aboutOpenOnGithub: 'about-open-on-github',
  aboutOpossumUiNotices: 'about-opossum-ui-notices',
  application: 'application',
  clearRecent: 'clear-recent',
  copy: 'copy',
  cut: 'cut',
  edit: 'edit',
  export: 'export',
  exportCompactBom: 'export-compact-bom',
  exportDetailedBom: 'export-detailed-bom',
  exportFollowUp: 'export-follow-up',
  exportSpdxJson: 'export-spdx-json',
  exportSpdxYaml: 'export-spdx-yaml',
  forceUnlock: 'force-unlock',
  helpCheckForUpdates: 'help-check-for-updates',
  helpOpenLogFiles: 'help-open-log-files',
  helpUserGuide: 'help-user-guide',
  help: 'help',
  import: 'import',
  importLegacyOpossumFile: 'import-legacy-opossum-file',
  importOwaspDependencyCheckFile: 'import-owasp-dependency-check-file',
  importScanCodeFile: 'import-scancode-file',
  mergeOpossumFiles: 'merge-opossum-files',
  openFile: 'open-file',
  openRecent: 'open-recent',
  paste: 'paste',
  projectMetadata: 'project-metadata',
  projectStatistics: 'project-statistics',
  qaMode: 'qa-mode',
  quit: 'quit',
  redo: 'redo',
  saveFile: 'save-file',
  searchAttributions: 'search-attributions',
  searchLinkedResources: 'search-linked-resources',
  searchResources: 'search-resources',
  searchSignals: 'search-signals',
  selectAll: 'select-all',
  setBaseUrl: 'set-base-url',
  showClassifications: 'show-classifications',
  showCriticality: 'show-criticality',
  splitOpossumFile: 'split-opossum-file',
  undo: 'undo',
  viewShowDevTools: 'view-show-dev-tools',
  viewToggleFullScreen: 'view-toggle-full-screen',
  view: 'view',
  viewZoomIn: 'view-zoom-in',
  viewZoomOut: 'view-zoom-out',
  file: 'file',
} as const;
