# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Check license compliance

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  check-license-compliance:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    steps:
      - uses: actions/checkout@v4

      - uses: fsfe/reuse-action@v5
