# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Check code quality

on:
  push:
    branches:
      - main
      - 'renovate/*'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    if: |
      !(github.event_name == 'pull_request' && startsWith(github.head_ref, 'renovate/'))
    env:
      CI: true
      TARGET_BRANCH: origin/${{ github.event_name == 'pull_request' && github.base_ref || 'main' }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v5
        with:
          cache: 'yarn'
          node-version: 22.20.0

      - run: yarn install --immutable

      - run: yarn format-check

      - run: yarn lint-commits

      - run: yarn lint-check

      - run: yarn typecheck

      - run: yarn circular-import-check

      - run: yarn knip

      - run: yarn test:unit
