# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            FILE: release/linux/OpossumUI-for-linux.AppImage
          - os: macos-latest
            FILE: release/mac/OpossumUI-for-mac.zip
          - os: windows-latest
            FILE: release/win/OpossumUI-for-win.exe

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 22

      - run: yarn install --immutable

      - run: yarn ship:auto

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.FILE }}

      - name: Upload user guide
        uses: softprops/action-gh-release@v2
        with:
          files: USER_GUIDE.md

      - name: Create SPDX document
        run: yarn spdx

      - name: Upload SPDX document
        uses: softprops/action-gh-release@v2
        with:
          files: opossum-ui.spdx.json
