# SPDX-FileCopyrightText: Meta Platforms, Inc. and its affiliates
# SPDX-FileCopyrightText: TNG Technology Consulting GmbH <https://www.tngtech.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Publish release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-command: yarn ship-linux
            FILES: |
              release/linux/OpossumUI-for-linux.AppImage
              release/linux/OpossumUI-for-linux.snap
          - os: macos-latest
            build-command: yarn ship-mac:x64
            FILES: release/mac/OpossumUI-for-mac-intel.zip
          - os: macos-latest
            build-command: yarn ship-mac:arm64
            FILES: release/mac-arm64/OpossumUI-for-mac-arm64.zip
          - os: windows-latest
            build-command: yarn ship-win
            FILES: release/win/OpossumUI-for-win.exe

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 22.19.0

      - run: yarn install --immutable

      - run: ${{ matrix.build-command }}

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.FILES }}

  upload-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: 22.19.0

      - run: yarn install --immutable

      - name: Create SPDX document
        run: yarn spdx

      - name: Upload user guide and SPDX document
        uses: softprops/action-gh-release@v2
        with:
          files: |
            USER_GUIDE.md
            opossum-ui.spdx.json
